apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # "root" codificado em Base64
  MYSQL_USER: c29hdA== # "soat" codificado em Base64
  MYSQL_PASSWORD: c29hdA== # "soat" codificado em Base64
