apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: soat
  template:
    metadata:
      labels:
        app: soat
    spec:
      containers:
        - name: soat
          image: ghcr.io/dougb60/node-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          command: ["npm", "run", "dev"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
